kind = "DojoContract"
class_hash = "0x78ce93e9a2addce15a0fc17b9386c2d272a0676a29586aa82e9e6d4ed18455c"
original_class_hash = "0x78ce93e9a2addce15a0fc17b9386c2d272a0676a29586aa82e9e6d4ed18455c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/depths_of_dread-actions-8ef963d7.json"
reads = []
writes = []
init_calldata = []
tag = "depths_of_dread-actions"
manifest_name = "depths_of_dread-actions-8ef963d7"
