kind = "DojoContract"
class_hash = "0x5b9c8ce716a1705a9af2db959514e84f6e3a58c5f890580dc77c5a893b64e07"
original_class_hash = "0x5b9c8ce716a1705a9af2db959514e84f6e3a58c5f890580dc77c5a893b64e07"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/depths_of_dread-actions-8ef963d7.json"
reads = []
writes = []
init_calldata = []
tag = "depths_of_dread-actions"
manifest_name = "depths_of_dread-actions-8ef963d7"
