tag = "depths_of_dread-actions"
writes = [
    "depths_of_dread-PlayerData",
    "depths_of_dread-PlayerState",
    "depths_of_dread-PlayerPowerUps",
    "depths_of_dread-GameData",
    "depths_of_dread-GameFloor",
    "depths_of_dread-GameCoins",
    "depths_of_dread-GameObstacles",
]
