[world]
name = "Depths of Dread"
description = "Rogue-like game build in Dojo."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/joeperpetua/depths-of-dread-backend"
seed = "depths_of_dread"

[world.socials]
x = "https://x.com/fernelabs"
github = "https://github.com/joeperpetua/depths-of-dread-backend"

[namespace]
default = "depths_of_dread"

[env]
rpc_url = "https://api.cartridge.gg/x/dod-dev/katana"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x03cae44b2932cf573cad525396df80a09a6897aafc6b9cb2deb5e5b68e5e38e9"

[writers]
"depths_of_dread" = ["depths_of_dread-actions"]
