[world]
name = "Depths of Dread"
description = "Rogue-like game build in Dojo."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/joeperpetua/depths-of-dread-backend"
seed = "depths_of_dread"

[world.socials]
x = "https://x.com/fernelabs"
github = "https://github.com/joeperpetua/depths-of-dread-backend"

[namespace]
default = "depths_of_dread"

[env]
rpc_url = "https://api.cartridge.gg/x/depths-of-dread/katana"
# Default account for katana with seed = 0
account_address = "0x6d7d5b6770f30163c5594c15fae190ad21ea234887df606cbb79102cf08f943"
private_key = "0x1ad315766eb5e76e4947a95747cecf6ed68ad922074c143063a9b3e5374cfe3"
world_address = "0x07cf7cffb289c9ead92e24793cab5a09f1399bf8827b3a6b7ef892a895f71b29"

[writers]
"depths_of_dread" = ["depths_of_dread-actions"]
