kind = "DojoModel"
class_hash = "0x7144f4e2ab74c442981a158160ab562d02c39cc9db15a32d42cf1511f52b829"
original_class_hash = "0x7144f4e2ab74c442981a158160ab562d02c39cc9db15a32d42cf1511f52b829"
abi = "manifests/dev/base/abis/models/depths_of_dread-PlayerPowerUps-17f0fa15.json"
tag = "depths_of_dread-PlayerPowerUps"
manifest_name = "depths_of_dread-PlayerPowerUps-17f0fa15"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "powers"
type = "Array<PowerUp>"
key = false
