kind = "DojoModel"
class_hash = "0x45af7e0c947981c027764f413f0eb755dc4444b4c64a5be685f281a92c6ec03"
original_class_hash = "0x45af7e0c947981c027764f413f0eb755dc4444b4c64a5be685f281a92c6ec03"
abi = "manifests/dev/base/abis/models/depths_of_dread-PlayerState-3df47c5a.json"
tag = "depths_of_dread-PlayerState"
manifest_name = "depths_of_dread-PlayerState-3df47c5a"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "usize"
key = false

[[members]]
name = "current_floor"
type = "u16"
key = false

[[members]]
name = "position"
type = "Vec2"
key = false

[[members]]
name = "coins"
type = "u16"
key = false
