kind = "DojoModel"
class_hash = "0x774297705e25938386e07ccf04343c16d7ef99122ebaa659683a8649f25d425"
original_class_hash = "0x774297705e25938386e07ccf04343c16d7ef99122ebaa659683a8649f25d425"
abi = "manifests/dev/base/abis/models/depths_of_dread-GameCoins-1168e538.json"
tag = "depths_of_dread-GameCoins"
manifest_name = "depths_of_dread-GameCoins-1168e538"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "position"
type = "Array<Vec2>"
key = false
