kind = "DojoModel"
class_hash = "0x4982e06b348cfa15a977afae70572039f166eecffd041299a117c0bb9ed4d74"
original_class_hash = "0x4982e06b348cfa15a977afae70572039f166eecffd041299a117c0bb9ed4d74"
abi = "manifests/dev/base/abis/models/depths_of_dread-GameCoins-1168e538.json"
tag = "depths_of_dread-GameCoins"
manifest_name = "depths_of_dread-GameCoins-1168e538"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "coins"
type = "Array<GameCoin>"
key = false
