kind = "DojoModel"
class_hash = "0x376d661902300f2ad57b208fc8f7a049c8c2ff82c4245cf02bcb87016423105"
original_class_hash = "0x376d661902300f2ad57b208fc8f7a049c8c2ff82c4245cf02bcb87016423105"
abi = "manifests/dev/base/abis/models/depths_of_dread-GameCoins-1168e538.json"
tag = "depths_of_dread-GameCoins"
manifest_name = "depths_of_dread-GameCoins-1168e538"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "coins"
type = "Array<Vec2>"
key = false
