kind = "DojoModel"
class_hash = "0x5eba209114bbf8a9ea0566be9fa57c263f96c00aa75ce10ff35ac1d336d4df8"
original_class_hash = "0x5eba209114bbf8a9ea0566be9fa57c263f96c00aa75ce10ff35ac1d336d4df8"
abi = "manifests/dev/base/abis/models/depths_of_dread-Moved-2d4e9587.json"
tag = "depths_of_dread-Moved"
manifest_name = "depths_of_dread-Moved-2d4e9587"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
