kind = "DojoModel"
class_hash = "0x42680802d7d2fece81586c85a04970e03f7554720f229e3aaf2f35c9a97604f"
original_class_hash = "0x42680802d7d2fece81586c85a04970e03f7554720f229e3aaf2f35c9a97604f"
abi = "manifests/dev/base/abis/models/depths_of_dread-GameObstacles-28fd6041.json"
tag = "depths_of_dread-GameObstacles"
manifest_name = "depths_of_dread-GameObstacles-28fd6041"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "instances"
type = "Array<Obstacle>"
key = false
